Add controllers
RuslanDergachev/java-shareit pull request #1
Opened 2022-07-25 15:36 UTC by RuslanDergachev

Реализовал UserController и ItemController

2022-07-26 13:32 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/booking/Booking.java
> +    BookingStatus status;
поля должны быть private,

применимо к аналагичным местам

2022-07-26 13:32 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/ItemMapper.java
> +                );
есть мнение, что в конструктор лучше не передавать больше 3-4 аргументов, это ухудшает восприятие кода,
как альтернатива, использовать билдер

исправлять или нет, на твое усмотрение

2022-07-26 13:32 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/Item.java
> +package ru.practicum.shareIt.item;
можно сразу добавить пекеджы controller, service и др.,
что бы потом, когда будут появляться новые контроллеры/сервисы относящиеся к айтему, не пришлось все разносить по соответствующим пакетам

в др. подобных местах аналагично

2022-07-26 13:32 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/ItemServiceImpl.java
> +
лишняя строка

2022-07-26 13:32 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/ItemServiceImpl.java
> +            throw new NullPointerException("ID меньше или равно 0");
лучше выбрасывать свое кастомное исключение, т.к. NPE - это привычное и знакомое по другому плану 

аналагично в др местах

2022-07-26 13:32 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/ItemServiceImpl.java
> +            log.info("Пользователь \"+userId+\" не существует");
лчше использовать плейсхолдер для логгера
log.info("Пользователь {} не существует", userId) ;
так лог выглядет лучше 
+ конкатенация строк не будет просходить до того момента, пока лог не будет выведен, в отличе от простого подхода

2022-07-26 13:49 UTC, Fleaman777 requested changes

2022-07-26 13:49 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/ItemStorage.java
> +        }
этот foreach можно было бы сделать в виде стрима

аналагично в подобных местах

2022-07-26 13:49 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/ItemStorage.java
> +        }
тут тоже напрашивается подход со стримом,

посмотри по коду, там где используется foreach - это потенциальное место для стрима, 
не всегда он конечно может быть применим или применим, но не очень красиво, 
но пока не попробоуешь, не узнаешь :)

2022-07-26 13:49 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/ItemStorage.java
> +                log.info("Вещь ID# "+itemId+" удалена");
здесь тоже применим плейсхолдер {}

2022-07-26 13:49 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/user/UserStorage.java
> +                throw new IOException("Такой пользователь уже существует");
что бы каждый раз не обрабатывать это исключение в методах которые будут использовать метод creat, лучше пробросить какое-нибудь рантайм исключение, возможно даже кастомное

2022-07-26 13:49 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/user/UserStorage.java
> +            for (User userMail : users.values()) {
все же, чуть более подходящее название будет User user, вместо userMail

2022-07-26 15:41 UTC, RuslanDergachev commented on src/main/java/ru/practicum/shareIt/item/Item.java
> +package ru.practicum.shareIt.item;
В задании прямо указано так (В этом модуле вы будете использовать структуру не по типам классов, а по фичам (англ. Feature layout) — весь код для работы с определённой сущностью должен быть в одном пакете. Поэтому сразу создайте четыре пакета — item, booking, request и user. В каждом из этих пакетов будут свои контроллеры, сервисы, репозитории и другие классы, которые вам понадобятся в ходе разработки. В пакете item создайте класс Item .)

2022-07-27 08:18 UTC, Fleaman777 requested changes

2022-07-27 08:18 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/ItemController.java
> +    public Optional<ItemDto> getItemById(@RequestHeader("X-Sharer-User-Id") long userId, @PathVariable long itemId) {
лучше из контроллера не возвращать Optional, 

Optional класс обертка, которая помогает безопасно работать с объектами внутри приложения, а наружу луччше отдавать готовый dto объект

2022-07-27 08:18 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/ItemStorage.java
> +                .map(ItemMapper::toItemDto);
отлично, совсем другой вид

2022-08-14 12:02 UTC, merged