Add bookings
RuslanDergachev/java-shareit pull request #2
Opened 2022-08-14 12:03 UTC by RuslanDergachev

Реализована опция бронирования, отзывов

2022-08-16 07:12 UTC, Fleaman777 requested changes

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/booking/Booking.java
>  package ru.practicum.shareIt.booking;
похоже пришло время добавить подпакеты
controller, service, .... 
так структура будет привычней :)

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/booking/BookingController.java
> +        }
валидацию лучше перенести в сервис, 
а в контроллер методах оставить только вызов сервиса

какую-то валидацию, которая испольщуется в нескольких местах, можно вынести в отдельные валидационные методы

аналагично в похожих местах

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/booking/BookingMapper.java
> +                null
этот маппинг тоже можно сделать через билдер

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/booking/BookingServiceImpl.java
> +                    .collect(Collectors.toList());
логику в блоках if можно было бы вынести в отдельные вспомагательные методы, так объем основного метода уменьшится и будет легче восприниматься

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/booking/BookingServiceImpl.java
> +        }
попробуй общую часть логики в этих if'ах как-нибудь вынести в один метод, 
и объем сократиться и читаться мб полегче будет

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/booking/BookingServiceImpl.java
> +        }
в этом классе тоже есть общая валидация, которую можно было бы вынести в приватные методы

в других похожих классах аналагично

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/comments/Comment.java
> +    LocalDateTime created;
про инкапсуляцю не забываем, 
поля должны быть приватными

в других похожих классах аналагично

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/comments/CommentServiceImpl.java
> +    ItemService itemService;
поля должны быть private

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/ItemServiceImpl.java
> +        List<Booking> bookings2 = booking.stream().sorted(comparing(Booking::getEnd).reversed())
bookings2 - лучше было бы переименовать во что-то чуть более говорящее

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/ItemServiceImpl.java
> +                            .getAuthorId()).getName())).collect(Collectors.toList());
отформатированный стрим полегче воспринимается

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/ItemServiceImpl.java
> +                    .collect(Collectors.toList());
такая логика получения bookings и bookings1 у тебя уже была, поэтому ее можно было тоже вынести в отедльный метод, 
а в иделе, объеденить, и сделать 1 общий метод, с подходящим аргументом

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/Item.java
> +    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
возможно, здесь лучше бы подошел FetchType.LAZY

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/resources/schema.sql
> +    start_date timestamp,
можешь добавить установку дефолтного значения now, если время старта не будет передано

2022-08-16 07:12 UTC, Fleaman777 commented on src/main/resources/schema.sql
> +);
для восприятия 
описание таблиц лучше сделать все в одном стиле, или в верхнем регичтре или в нижнем, 
и с одинаковыми отступомами,

2022-08-16 12:05 UTC, RuslanDergachev commented on src/main/java/ru/practicum/shareIt/booking/BookingServiceImpl.java
> +                    .collect(Collectors.toList());
Логика в каждом блоке if разная

2022-08-17 12:04 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/booking/BookingServiceImpl.java
> +                    .collect(Collectors.toList());
ага, 
поэтому можно сделать раздельные приватные методы, для каждого if свой

2022-08-17 12:20 UTC, Fleaman777 approved these changes

2022-08-17 12:20 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/booking/entity/Booking.java
> +package ru.practicum.shareIt.booking.entity;
хорошее разделение на пакеты, в целом все как надо, но 1 момент можно было бы поправть: 

обычно, пекедж entity используют для модельных классов, которые описывают таблицы, 
а в пекедже dto, dto классы для респонсов/реквестов 

в свою очередь, эти пакеты можно сложить в model

2022-08-18 16:15 UTC, merged