ФП 15 спринта, написал кучу тестов
RuslanDergachev/java-shareit pull request #3
Opened 2022-08-27 16:47 UTC by RuslanDergachev

ФП 15 спринта 1 ревью

2022-08-28 18:41 UTC, Fleaman777 requested changes

2022-08-28 18:41 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/item/service/ItemServiceImpl.java
> +            return new ArrayList<>();
как еще один враиант вернуть пустой списко, использзовать Collections.emptyList()

2022-08-28 18:41 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/request/controller/RequestController.java
> +    public ItemRequestDto add(@RequestHeader("X-Sharer-User-Id") long userId,
X-Sharer-User-Id - можно вынести, в общую для всех классов, константу,

2022-08-28 18:41 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/request/model/entity/ItemRequest.java
> +    Long requestorId;
поля должны быть приватные

2022-08-28 18:41 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/request/service/ItemRequestServiceImpl.java
> +    ItemRepository itemRepository;
и тут прайват

2022-08-28 18:41 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/request/service/ItemRequestServiceImpl.java
> +        ItemRequest itemRequest = ItemRequestMapper.toItemRequest(itemRequestDto);
как вариант, в метод toItemRequest вторым параметром можно добавить юзерАйди, тогда не нужно будет писать     
 itemRequest.setRequestorId(userId);

2022-08-28 18:41 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareIt/request/service/ItemRequestServiceImpl.java
> +        return itemRequestDtos;
можно сразу вернуть результат стрима, не используя локальнуые переменные itemRequests и itemRequestDtos

2022-08-28 18:41 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareIt/booking/controller/BookingControllerTest.java
> +    void getBookingsTest() throws Exception {
как еще один варинат названия для тестов: 
shouldReturn....WhenGetBookingsWhen....

2022-08-28 18:41 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareIt/comments/service/CommentServiceImplTest.java
> +        Comment comment = Comment.builder()
общие тестовые комменты можно вынести в константы

2022-08-28 18:41 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareIt/item/controller/ItemControllerTest.java
> +            null
хорошо было бы использовать билдер, тогда было бы лучше понятно, что именно в ДТО будет null

2022-08-28 18:41 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareIt/request/service/ItemRequestServiceImplTest.java
> +    Logger log;
в тестах тоже можно следовать инкапсуляции, и делать поля private

2022-08-28 18:41 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareIt/request/service/ItemRequestServiceImplTest.java
> +        Assertions.assertEquals("Запрос пользователя ID 1 пустой", exception.getMessage());
точно не помню, но вроде бь у библиотеки Assertions можно как-то сразу и проверить какое исключение вылетит, и какое сообщение оно содержит, без соранения эксепшена в доп переменную, 

посмотри, может получится что-то подобное найти

2022-08-29 11:59 UTC, RuslanDergachev commented on src/test/java/ru/practicum/shareIt/request/service/ItemRequestServiceImplTest.java
> +        Assertions.assertEquals("Запрос пользователя ID 1 пустой", exception.getMessage());
Поискал, лучшим решением указано применяемое мной. В документации предлагаемое решение такое-же.

2022-08-29 20:41 UTC, Fleaman777 approved these changes

2022-09-02 07:28 UTC, merged